/* Generated by Yosys 0.57 (git sha1 3aca86049, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "adder" *)
(* src = "adder.sv:1.8-1.13" *)
module adder(reset_i, ready_i, valid_i, a_i, b_i, ready_o, valid_o, c_o, clk_i);
  (* src = "adder.sv:6.16-6.23" *)
  input [0:0] reset_i;
  wire [0:0] reset_i;
  (* src = "adder.sv:7.16-7.23" *)
  input [0:0] ready_i;
  wire [0:0] ready_i;
  (* src = "adder.sv:8.16-8.23" *)
  input [0:0] valid_i;
  wire [0:0] valid_i;
  (* src = "adder.sv:9.26-9.29" *)
  input [31:0] a_i;
  wire [31:0] a_i;
  (* src = "adder.sv:10.26-10.29" *)
  input [31:0] b_i;
  wire [31:0] b_i;
  (* src = "adder.sv:11.17-11.24" *)
  output [0:0] ready_o;
  wire [0:0] ready_o;
  (* src = "adder.sv:12.17-12.24" *)
  output [0:0] valid_o;
  wire [0:0] valid_o;
  (* src = "adder.sv:13.23-13.26" *)
  output [32:0] c_o;
  wire [32:0] c_o;
  (* src = "adder.sv:5.16-5.21" *)
  input [0:0] clk_i;
  wire [0:0] clk_i;
  (* force_downto = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 28 29 30 32" *)
  wire [32:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [32:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 20 21 22 24 25 26 28 29 30 32 33 34 35" *)
  wire [35:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "33 34 35" *)
  wire [35:0] _003_;
  (* unused_bits = "0" *)
  wire _004_;
  wire _005_;
  (* unused_bits = "0" *)
  wire _006_;
  wire _007_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _038_;
  (* force_downto = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _039_;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _040_ (
    .I0(_039_[0]),
    .I1(_039_[1]),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _041_ (
    .I0(_038_[0]),
    .I1(_038_[1]),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _042_ (
    .I0(_037_[0]),
    .I1(_037_[1]),
    .O(_001_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _043_ (
    .I0(_036_[0]),
    .I1(_036_[1]),
    .O(_001_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _044_ (
    .I0(_035_[0]),
    .I1(_035_[1]),
    .O(_001_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _045_ (
    .I0(_034_[0]),
    .I1(_034_[1]),
    .O(_001_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _046_ (
    .I0(_033_[0]),
    .I1(_033_[1]),
    .O(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _047_ (
    .I0(_032_[0]),
    .I1(_032_[1]),
    .O(_001_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _048_ (
    .I0(_031_[0]),
    .I1(_031_[1]),
    .O(_001_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _049_ (
    .I0(_030_[0]),
    .I1(_030_[1]),
    .O(_001_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _050_ (
    .I0(_029_[0]),
    .I1(_029_[1]),
    .O(_001_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _051_ (
    .I0(_028_[0]),
    .I1(_028_[1]),
    .O(_001_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _052_ (
    .I0(_027_[0]),
    .I1(_027_[1]),
    .O(_001_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _053_ (
    .I0(_026_[0]),
    .I1(_026_[1]),
    .O(_001_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _054_ (
    .I0(_025_[0]),
    .I1(_025_[1]),
    .O(_001_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _055_ (
    .I0(_024_[0]),
    .I1(_024_[1]),
    .O(_001_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _056_ (
    .I0(_023_[0]),
    .I1(_023_[1]),
    .O(_001_[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _057_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .O(_001_[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _058_ (
    .I0(_016_[0]),
    .I1(_016_[1]),
    .O(_001_[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _059_ (
    .I0(_015_[0]),
    .I1(_015_[1]),
    .O(_001_[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _060_ (
    .I0(_018_[0]),
    .I1(_018_[1]),
    .O(_001_[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _061_ (
    .I0(_019_[0]),
    .I1(_019_[1]),
    .O(_001_[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _062_ (
    .I0(_020_[0]),
    .I1(_020_[1]),
    .O(_001_[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _063_ (
    .I0(_021_[0]),
    .I1(_021_[1]),
    .O(_001_[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _064_ (
    .I0(_022_[0]),
    .I1(_022_[1]),
    .O(_001_[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _065_ (
    .I0(_008_[0]),
    .I1(_008_[1]),
    .O(_001_[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _066_ (
    .I0(_010_[0]),
    .I1(_010_[1]),
    .O(_001_[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _067_ (
    .I0(_009_[0]),
    .I1(_009_[1]),
    .O(_001_[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _068_ (
    .I0(_011_[0]),
    .I1(_011_[1]),
    .O(_001_[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _069_ (
    .I0(_014_[0]),
    .I1(_014_[1]),
    .O(_001_[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _070_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .O(_001_[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/tabby/lib/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h6)
  ) _071_ (
    .I0(_012_[0]),
    .I1(_012_[1]),
    .O(_001_[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _072_ (
    .CI(1'h0),
    .CO(_000_[3:0]),
    .CYINIT(1'h0),
    .DI({ _036_[0], _037_[0], _038_[0], _039_[0] }),
    .O(_003_[3:0]),
    .S(_001_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _073_ (
    .CI(_000_[3]),
    .CO(_000_[7:4]),
    .CYINIT(1'h0),
    .DI({ _032_[0], _033_[0], _034_[0], _035_[0] }),
    .O(_003_[7:4]),
    .S(_001_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _074_ (
    .CI(_000_[7]),
    .CO(_000_[11:8]),
    .CYINIT(1'h0),
    .DI({ _028_[0], _029_[0], _030_[0], _031_[0] }),
    .O(_003_[11:8]),
    .S(_001_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _075_ (
    .CI(_000_[11]),
    .CO(_000_[15:12]),
    .CYINIT(1'h0),
    .DI({ _024_[0], _025_[0], _026_[0], _027_[0] }),
    .O(_003_[15:12]),
    .S(_001_[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _076_ (
    .CI(_000_[15]),
    .CO(_000_[19:16]),
    .CYINIT(1'h0),
    .DI({ _015_[0], _016_[0], _017_[0], _023_[0] }),
    .O(_003_[19:16]),
    .S(_001_[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _077_ (
    .CI(_000_[19]),
    .CO(_000_[23:20]),
    .CYINIT(1'h0),
    .DI({ _021_[0], _020_[0], _019_[0], _018_[0] }),
    .O(_003_[23:20]),
    .S(_001_[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _078_ (
    .CI(_000_[23]),
    .CO(_000_[27:24]),
    .CYINIT(1'h0),
    .DI({ _009_[0], _010_[0], _008_[0], _022_[0] }),
    .O(_003_[27:24]),
    .S(_001_[27:24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _079_ (
    .CI(_000_[27]),
    .CO(_000_[31:28]),
    .CYINIT(1'h0),
    .DI({ _012_[0], _013_[0], _014_[0], _011_[0] }),
    .O(_003_[31:28]),
    .S(_001_[31:28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "adder.sv:19.16-19.25|/usr/local/bin/tabby/lib/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _080_ (
    .CI(_000_[31]),
    .CO({ _002_[35:33], _000_[32] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_003_[35:32]),
    .S(4'h0)
  );
  (* keep = 32'd1 *)
  IBUF _081_ (
    .I(a_i[0]),
    .O(_039_[0])
  );
  (* keep = 32'd1 *)
  IBUF _082_ (
    .I(a_i[1]),
    .O(_038_[0])
  );
  (* keep = 32'd1 *)
  IBUF _083_ (
    .I(a_i[10]),
    .O(_029_[0])
  );
  (* keep = 32'd1 *)
  IBUF _084_ (
    .I(a_i[11]),
    .O(_028_[0])
  );
  (* keep = 32'd1 *)
  IBUF _085_ (
    .I(a_i[12]),
    .O(_027_[0])
  );
  (* keep = 32'd1 *)
  IBUF _086_ (
    .I(a_i[13]),
    .O(_026_[0])
  );
  (* keep = 32'd1 *)
  IBUF _087_ (
    .I(a_i[14]),
    .O(_025_[0])
  );
  (* keep = 32'd1 *)
  IBUF _088_ (
    .I(a_i[15]),
    .O(_024_[0])
  );
  (* keep = 32'd1 *)
  IBUF _089_ (
    .I(a_i[16]),
    .O(_023_[0])
  );
  (* keep = 32'd1 *)
  IBUF _090_ (
    .I(a_i[17]),
    .O(_017_[0])
  );
  (* keep = 32'd1 *)
  IBUF _091_ (
    .I(a_i[18]),
    .O(_016_[0])
  );
  (* keep = 32'd1 *)
  IBUF _092_ (
    .I(a_i[19]),
    .O(_015_[0])
  );
  (* keep = 32'd1 *)
  IBUF _093_ (
    .I(a_i[2]),
    .O(_037_[0])
  );
  (* keep = 32'd1 *)
  IBUF _094_ (
    .I(a_i[20]),
    .O(_018_[0])
  );
  (* keep = 32'd1 *)
  IBUF _095_ (
    .I(a_i[21]),
    .O(_019_[0])
  );
  (* keep = 32'd1 *)
  IBUF _096_ (
    .I(a_i[22]),
    .O(_020_[0])
  );
  (* keep = 32'd1 *)
  IBUF _097_ (
    .I(a_i[23]),
    .O(_021_[0])
  );
  (* keep = 32'd1 *)
  IBUF _098_ (
    .I(a_i[24]),
    .O(_022_[0])
  );
  (* keep = 32'd1 *)
  IBUF _099_ (
    .I(a_i[25]),
    .O(_008_[0])
  );
  (* keep = 32'd1 *)
  IBUF _100_ (
    .I(a_i[26]),
    .O(_010_[0])
  );
  (* keep = 32'd1 *)
  IBUF _101_ (
    .I(a_i[27]),
    .O(_009_[0])
  );
  (* keep = 32'd1 *)
  IBUF _102_ (
    .I(a_i[28]),
    .O(_011_[0])
  );
  (* keep = 32'd1 *)
  IBUF _103_ (
    .I(a_i[29]),
    .O(_014_[0])
  );
  (* keep = 32'd1 *)
  IBUF _104_ (
    .I(a_i[3]),
    .O(_036_[0])
  );
  (* keep = 32'd1 *)
  IBUF _105_ (
    .I(a_i[30]),
    .O(_013_[0])
  );
  (* keep = 32'd1 *)
  IBUF _106_ (
    .I(a_i[31]),
    .O(_012_[0])
  );
  (* keep = 32'd1 *)
  IBUF _107_ (
    .I(a_i[4]),
    .O(_035_[0])
  );
  (* keep = 32'd1 *)
  IBUF _108_ (
    .I(a_i[5]),
    .O(_034_[0])
  );
  (* keep = 32'd1 *)
  IBUF _109_ (
    .I(a_i[6]),
    .O(_033_[0])
  );
  (* keep = 32'd1 *)
  IBUF _110_ (
    .I(a_i[7]),
    .O(_032_[0])
  );
  (* keep = 32'd1 *)
  IBUF _111_ (
    .I(a_i[8]),
    .O(_031_[0])
  );
  (* keep = 32'd1 *)
  IBUF _112_ (
    .I(a_i[9]),
    .O(_030_[0])
  );
  (* keep = 32'd1 *)
  IBUF _113_ (
    .I(b_i[0]),
    .O(_039_[1])
  );
  (* keep = 32'd1 *)
  IBUF _114_ (
    .I(b_i[1]),
    .O(_038_[1])
  );
  (* keep = 32'd1 *)
  IBUF _115_ (
    .I(b_i[10]),
    .O(_029_[1])
  );
  (* keep = 32'd1 *)
  IBUF _116_ (
    .I(b_i[11]),
    .O(_028_[1])
  );
  (* keep = 32'd1 *)
  IBUF _117_ (
    .I(b_i[12]),
    .O(_027_[1])
  );
  (* keep = 32'd1 *)
  IBUF _118_ (
    .I(b_i[13]),
    .O(_026_[1])
  );
  (* keep = 32'd1 *)
  IBUF _119_ (
    .I(b_i[14]),
    .O(_025_[1])
  );
  (* keep = 32'd1 *)
  IBUF _120_ (
    .I(b_i[15]),
    .O(_024_[1])
  );
  (* keep = 32'd1 *)
  IBUF _121_ (
    .I(b_i[16]),
    .O(_023_[1])
  );
  (* keep = 32'd1 *)
  IBUF _122_ (
    .I(b_i[17]),
    .O(_017_[1])
  );
  (* keep = 32'd1 *)
  IBUF _123_ (
    .I(b_i[18]),
    .O(_016_[1])
  );
  (* keep = 32'd1 *)
  IBUF _124_ (
    .I(b_i[19]),
    .O(_015_[1])
  );
  (* keep = 32'd1 *)
  IBUF _125_ (
    .I(b_i[2]),
    .O(_037_[1])
  );
  (* keep = 32'd1 *)
  IBUF _126_ (
    .I(b_i[20]),
    .O(_018_[1])
  );
  (* keep = 32'd1 *)
  IBUF _127_ (
    .I(b_i[21]),
    .O(_019_[1])
  );
  (* keep = 32'd1 *)
  IBUF _128_ (
    .I(b_i[22]),
    .O(_020_[1])
  );
  (* keep = 32'd1 *)
  IBUF _129_ (
    .I(b_i[23]),
    .O(_021_[1])
  );
  (* keep = 32'd1 *)
  IBUF _130_ (
    .I(b_i[24]),
    .O(_022_[1])
  );
  (* keep = 32'd1 *)
  IBUF _131_ (
    .I(b_i[25]),
    .O(_008_[1])
  );
  (* keep = 32'd1 *)
  IBUF _132_ (
    .I(b_i[26]),
    .O(_010_[1])
  );
  (* keep = 32'd1 *)
  IBUF _133_ (
    .I(b_i[27]),
    .O(_009_[1])
  );
  (* keep = 32'd1 *)
  IBUF _134_ (
    .I(b_i[28]),
    .O(_011_[1])
  );
  (* keep = 32'd1 *)
  IBUF _135_ (
    .I(b_i[29]),
    .O(_014_[1])
  );
  (* keep = 32'd1 *)
  IBUF _136_ (
    .I(b_i[3]),
    .O(_036_[1])
  );
  (* keep = 32'd1 *)
  IBUF _137_ (
    .I(b_i[30]),
    .O(_013_[1])
  );
  (* keep = 32'd1 *)
  IBUF _138_ (
    .I(b_i[31]),
    .O(_012_[1])
  );
  (* keep = 32'd1 *)
  IBUF _139_ (
    .I(b_i[4]),
    .O(_035_[1])
  );
  (* keep = 32'd1 *)
  IBUF _140_ (
    .I(b_i[5]),
    .O(_034_[1])
  );
  (* keep = 32'd1 *)
  IBUF _141_ (
    .I(b_i[6]),
    .O(_033_[1])
  );
  (* keep = 32'd1 *)
  IBUF _142_ (
    .I(b_i[7]),
    .O(_032_[1])
  );
  (* keep = 32'd1 *)
  IBUF _143_ (
    .I(b_i[8]),
    .O(_031_[1])
  );
  (* keep = 32'd1 *)
  IBUF _144_ (
    .I(b_i[9]),
    .O(_030_[1])
  );
  (* keep = 32'd1 *)
  OBUF _145_ (
    .I(_003_[0]),
    .O(c_o[0])
  );
  (* keep = 32'd1 *)
  OBUF _146_ (
    .I(_003_[1]),
    .O(c_o[1])
  );
  (* keep = 32'd1 *)
  OBUF _147_ (
    .I(_003_[10]),
    .O(c_o[10])
  );
  (* keep = 32'd1 *)
  OBUF _148_ (
    .I(_003_[11]),
    .O(c_o[11])
  );
  (* keep = 32'd1 *)
  OBUF _149_ (
    .I(_003_[12]),
    .O(c_o[12])
  );
  (* keep = 32'd1 *)
  OBUF _150_ (
    .I(_003_[13]),
    .O(c_o[13])
  );
  (* keep = 32'd1 *)
  OBUF _151_ (
    .I(_003_[14]),
    .O(c_o[14])
  );
  (* keep = 32'd1 *)
  OBUF _152_ (
    .I(_003_[15]),
    .O(c_o[15])
  );
  (* keep = 32'd1 *)
  OBUF _153_ (
    .I(_003_[16]),
    .O(c_o[16])
  );
  (* keep = 32'd1 *)
  OBUF _154_ (
    .I(_003_[17]),
    .O(c_o[17])
  );
  (* keep = 32'd1 *)
  OBUF _155_ (
    .I(_003_[18]),
    .O(c_o[18])
  );
  (* keep = 32'd1 *)
  OBUF _156_ (
    .I(_003_[19]),
    .O(c_o[19])
  );
  (* keep = 32'd1 *)
  OBUF _157_ (
    .I(_003_[2]),
    .O(c_o[2])
  );
  (* keep = 32'd1 *)
  OBUF _158_ (
    .I(_003_[20]),
    .O(c_o[20])
  );
  (* keep = 32'd1 *)
  OBUF _159_ (
    .I(_003_[21]),
    .O(c_o[21])
  );
  (* keep = 32'd1 *)
  OBUF _160_ (
    .I(_003_[22]),
    .O(c_o[22])
  );
  (* keep = 32'd1 *)
  OBUF _161_ (
    .I(_003_[23]),
    .O(c_o[23])
  );
  (* keep = 32'd1 *)
  OBUF _162_ (
    .I(_003_[24]),
    .O(c_o[24])
  );
  (* keep = 32'd1 *)
  OBUF _163_ (
    .I(_003_[25]),
    .O(c_o[25])
  );
  (* keep = 32'd1 *)
  OBUF _164_ (
    .I(_003_[26]),
    .O(c_o[26])
  );
  (* keep = 32'd1 *)
  OBUF _165_ (
    .I(_003_[27]),
    .O(c_o[27])
  );
  (* keep = 32'd1 *)
  OBUF _166_ (
    .I(_003_[28]),
    .O(c_o[28])
  );
  (* keep = 32'd1 *)
  OBUF _167_ (
    .I(_003_[29]),
    .O(c_o[29])
  );
  (* keep = 32'd1 *)
  OBUF _168_ (
    .I(_003_[3]),
    .O(c_o[3])
  );
  (* keep = 32'd1 *)
  OBUF _169_ (
    .I(_003_[30]),
    .O(c_o[30])
  );
  (* keep = 32'd1 *)
  OBUF _170_ (
    .I(_003_[31]),
    .O(c_o[31])
  );
  (* keep = 32'd1 *)
  OBUF _171_ (
    .I(_003_[32]),
    .O(c_o[32])
  );
  (* keep = 32'd1 *)
  OBUF _172_ (
    .I(_003_[4]),
    .O(c_o[4])
  );
  (* keep = 32'd1 *)
  OBUF _173_ (
    .I(_003_[5]),
    .O(c_o[5])
  );
  (* keep = 32'd1 *)
  OBUF _174_ (
    .I(_003_[6]),
    .O(c_o[6])
  );
  (* keep = 32'd1 *)
  OBUF _175_ (
    .I(_003_[7]),
    .O(c_o[7])
  );
  (* keep = 32'd1 *)
  OBUF _176_ (
    .I(_003_[8]),
    .O(c_o[8])
  );
  (* keep = 32'd1 *)
  OBUF _177_ (
    .I(_003_[9]),
    .O(c_o[9])
  );
  (* keep = 32'd1 *)
  IBUF _178_ (
    .I(clk_i),
    .O(_004_)
  );
  (* keep = 32'd1 *)
  IBUF _179_ (
    .I(ready_i),
    .O(_005_)
  );
  (* keep = 32'd1 *)
  OBUF _180_ (
    .I(_005_),
    .O(ready_o)
  );
  (* keep = 32'd1 *)
  IBUF _181_ (
    .I(reset_i),
    .O(_006_)
  );
  (* keep = 32'd1 *)
  IBUF _182_ (
    .I(valid_i),
    .O(_007_)
  );
  (* keep = 32'd1 *)
  OBUF _183_ (
    .I(_007_),
    .O(valid_o)
  );
  assign _001_[32] = 1'h0;
  assign _002_[32:0] = _000_;
endmodule
