/* Generated by Yosys 0.57 (git sha1 3aca86049, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* \library  = "work" *)
(* hdlname = "multiplier" *)
(* src = "multiplier.sv:1.8-1.18" *)
module multiplier(reset_i, valid_i, a_i, b_i, ready_o, valid_o, c_o, ready_i, clk_i);
  (* src = "multiplier.sv:7.16-7.23" *)
  input [0:0] reset_i;
  wire [0:0] reset_i;
  (* src = "multiplier.sv:9.16-9.23" *)
  input [0:0] valid_i;
  wire [0:0] valid_i;
  (* src = "multiplier.sv:10.26-10.29" *)
  input [15:0] a_i;
  wire [15:0] a_i;
  (* src = "multiplier.sv:11.26-11.29" *)
  input [15:0] b_i;
  wire [15:0] b_i;
  (* src = "multiplier.sv:12.17-12.24" *)
  output [0:0] ready_o;
  wire [0:0] ready_o;
  (* src = "multiplier.sv:14.17-14.24" *)
  output [0:0] valid_o;
  wire [0:0] valid_o;
  (* src = "multiplier.sv:15.33-15.36" *)
  output [31:0] c_o;
  wire [31:0] c_o;
  (* src = "multiplier.sv:16.16-16.23" *)
  input [0:0] ready_i;
  wire [0:0] ready_i;
  (* src = "multiplier.sv:6.16-6.21" *)
  input [0:0] clk_i;
  wire [0:0] clk_i;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [15:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  wire [15:0] _03_;
  wire [31:0] _04_;
  (* unused_bits = "0" *)
  wire _05_;
  wire _06_;
  (* unused_bits = "0" *)
  wire _07_;
  wire _08_;
  (* keep = 32'd1 *)
  IBUF _09_ (
    .I(a_i[0]),
    .O(_02_[0])
  );
  (* keep = 32'd1 *)
  IBUF _10_ (
    .I(a_i[1]),
    .O(_02_[1])
  );
  (* keep = 32'd1 *)
  IBUF _11_ (
    .I(a_i[10]),
    .O(_02_[10])
  );
  (* keep = 32'd1 *)
  IBUF _12_ (
    .I(a_i[11]),
    .O(_02_[11])
  );
  (* keep = 32'd1 *)
  IBUF _13_ (
    .I(a_i[12]),
    .O(_02_[12])
  );
  (* keep = 32'd1 *)
  IBUF _14_ (
    .I(a_i[13]),
    .O(_02_[13])
  );
  (* keep = 32'd1 *)
  IBUF _15_ (
    .I(a_i[14]),
    .O(_02_[14])
  );
  (* keep = 32'd1 *)
  IBUF _16_ (
    .I(a_i[15]),
    .O(_02_[15])
  );
  (* keep = 32'd1 *)
  IBUF _17_ (
    .I(a_i[2]),
    .O(_02_[2])
  );
  (* keep = 32'd1 *)
  IBUF _18_ (
    .I(a_i[3]),
    .O(_02_[3])
  );
  (* keep = 32'd1 *)
  IBUF _19_ (
    .I(a_i[4]),
    .O(_02_[4])
  );
  (* keep = 32'd1 *)
  IBUF _20_ (
    .I(a_i[5]),
    .O(_02_[5])
  );
  (* keep = 32'd1 *)
  IBUF _21_ (
    .I(a_i[6]),
    .O(_02_[6])
  );
  (* keep = 32'd1 *)
  IBUF _22_ (
    .I(a_i[7]),
    .O(_02_[7])
  );
  (* keep = 32'd1 *)
  IBUF _23_ (
    .I(a_i[8]),
    .O(_02_[8])
  );
  (* keep = 32'd1 *)
  IBUF _24_ (
    .I(a_i[9]),
    .O(_02_[9])
  );
  (* keep = 32'd1 *)
  IBUF _25_ (
    .I(b_i[0]),
    .O(_03_[0])
  );
  (* keep = 32'd1 *)
  IBUF _26_ (
    .I(b_i[1]),
    .O(_03_[1])
  );
  (* keep = 32'd1 *)
  IBUF _27_ (
    .I(b_i[10]),
    .O(_03_[10])
  );
  (* keep = 32'd1 *)
  IBUF _28_ (
    .I(b_i[11]),
    .O(_03_[11])
  );
  (* keep = 32'd1 *)
  IBUF _29_ (
    .I(b_i[12]),
    .O(_03_[12])
  );
  (* keep = 32'd1 *)
  IBUF _30_ (
    .I(b_i[13]),
    .O(_03_[13])
  );
  (* keep = 32'd1 *)
  IBUF _31_ (
    .I(b_i[14]),
    .O(_03_[14])
  );
  (* keep = 32'd1 *)
  IBUF _32_ (
    .I(b_i[15]),
    .O(_03_[15])
  );
  (* keep = 32'd1 *)
  IBUF _33_ (
    .I(b_i[2]),
    .O(_03_[2])
  );
  (* keep = 32'd1 *)
  IBUF _34_ (
    .I(b_i[3]),
    .O(_03_[3])
  );
  (* keep = 32'd1 *)
  IBUF _35_ (
    .I(b_i[4]),
    .O(_03_[4])
  );
  (* keep = 32'd1 *)
  IBUF _36_ (
    .I(b_i[5]),
    .O(_03_[5])
  );
  (* keep = 32'd1 *)
  IBUF _37_ (
    .I(b_i[6]),
    .O(_03_[6])
  );
  (* keep = 32'd1 *)
  IBUF _38_ (
    .I(b_i[7]),
    .O(_03_[7])
  );
  (* keep = 32'd1 *)
  IBUF _39_ (
    .I(b_i[8]),
    .O(_03_[8])
  );
  (* keep = 32'd1 *)
  IBUF _40_ (
    .I(b_i[9]),
    .O(_03_[9])
  );
  (* keep = 32'd1 *)
  OBUF _41_ (
    .I(_04_[0]),
    .O(c_o[0])
  );
  (* keep = 32'd1 *)
  OBUF _42_ (
    .I(_04_[1]),
    .O(c_o[1])
  );
  (* keep = 32'd1 *)
  OBUF _43_ (
    .I(_04_[10]),
    .O(c_o[10])
  );
  (* keep = 32'd1 *)
  OBUF _44_ (
    .I(_04_[11]),
    .O(c_o[11])
  );
  (* keep = 32'd1 *)
  OBUF _45_ (
    .I(_04_[12]),
    .O(c_o[12])
  );
  (* keep = 32'd1 *)
  OBUF _46_ (
    .I(_04_[13]),
    .O(c_o[13])
  );
  (* keep = 32'd1 *)
  OBUF _47_ (
    .I(_04_[14]),
    .O(c_o[14])
  );
  (* keep = 32'd1 *)
  OBUF _48_ (
    .I(_04_[15]),
    .O(c_o[15])
  );
  (* keep = 32'd1 *)
  OBUF _49_ (
    .I(_04_[16]),
    .O(c_o[16])
  );
  (* keep = 32'd1 *)
  OBUF _50_ (
    .I(_04_[17]),
    .O(c_o[17])
  );
  (* keep = 32'd1 *)
  OBUF _51_ (
    .I(_04_[18]),
    .O(c_o[18])
  );
  (* keep = 32'd1 *)
  OBUF _52_ (
    .I(_04_[19]),
    .O(c_o[19])
  );
  (* keep = 32'd1 *)
  OBUF _53_ (
    .I(_04_[2]),
    .O(c_o[2])
  );
  (* keep = 32'd1 *)
  OBUF _54_ (
    .I(_04_[20]),
    .O(c_o[20])
  );
  (* keep = 32'd1 *)
  OBUF _55_ (
    .I(_04_[21]),
    .O(c_o[21])
  );
  (* keep = 32'd1 *)
  OBUF _56_ (
    .I(_04_[22]),
    .O(c_o[22])
  );
  (* keep = 32'd1 *)
  OBUF _57_ (
    .I(_04_[23]),
    .O(c_o[23])
  );
  (* keep = 32'd1 *)
  OBUF _58_ (
    .I(_04_[24]),
    .O(c_o[24])
  );
  (* keep = 32'd1 *)
  OBUF _59_ (
    .I(_04_[25]),
    .O(c_o[25])
  );
  (* keep = 32'd1 *)
  OBUF _60_ (
    .I(_04_[26]),
    .O(c_o[26])
  );
  (* keep = 32'd1 *)
  OBUF _61_ (
    .I(_04_[27]),
    .O(c_o[27])
  );
  (* keep = 32'd1 *)
  OBUF _62_ (
    .I(_04_[28]),
    .O(c_o[28])
  );
  (* keep = 32'd1 *)
  OBUF _63_ (
    .I(_04_[29]),
    .O(c_o[29])
  );
  (* keep = 32'd1 *)
  OBUF _64_ (
    .I(_04_[3]),
    .O(c_o[3])
  );
  (* keep = 32'd1 *)
  OBUF _65_ (
    .I(_04_[30]),
    .O(c_o[30])
  );
  (* keep = 32'd1 *)
  OBUF _66_ (
    .I(_04_[31]),
    .O(c_o[31])
  );
  (* keep = 32'd1 *)
  OBUF _67_ (
    .I(_04_[4]),
    .O(c_o[4])
  );
  (* keep = 32'd1 *)
  OBUF _68_ (
    .I(_04_[5]),
    .O(c_o[5])
  );
  (* keep = 32'd1 *)
  OBUF _69_ (
    .I(_04_[6]),
    .O(c_o[6])
  );
  (* keep = 32'd1 *)
  OBUF _70_ (
    .I(_04_[7]),
    .O(c_o[7])
  );
  (* keep = 32'd1 *)
  OBUF _71_ (
    .I(_04_[8]),
    .O(c_o[8])
  );
  (* keep = 32'd1 *)
  OBUF _72_ (
    .I(_04_[9]),
    .O(c_o[9])
  );
  (* keep = 32'd1 *)
  IBUF _73_ (
    .I(clk_i),
    .O(_05_)
  );
  (* keep = 32'd1 *)
  IBUF _74_ (
    .I(ready_i),
    .O(_06_)
  );
  (* keep = 32'd1 *)
  OBUF _75_ (
    .I(_06_),
    .O(ready_o)
  );
  (* keep = 32'd1 *)
  IBUF _76_ (
    .I(reset_i),
    .O(_07_)
  );
  (* keep = 32'd1 *)
  IBUF _77_ (
    .I(valid_i),
    .O(_08_)
  );
  (* keep = 32'd1 *)
  OBUF _78_ (
    .I(_08_),
    .O(valid_o)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "multiplier.sv:21.16-21.25|/usr/local/bin/tabby/lib/../share/yosys/mul2dsp.v:91.5-95.4|/usr/local/bin/tabby/lib/../share/yosys/mul2dsp.v:253.6-257.5|/usr/local/bin/tabby/lib/../share/yosys/xilinx/xc7_dsp_map.v:30.4-48.3" *)
  DSP48E1 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_DPORT("FALSE"),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _79_ (
    .A({ 14'h0000, _02_ }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 2'h0, _03_ }),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(25'h0000000),
    .INMODE(5'h00),
    .OPMODE(7'h05),
    .P({ _01_, _04_ }),
    .PCIN(48'h000000000000)
  );
endmodule
